import Link from "next/link";

export const metadata = {
  title: "Privacy Protocol — Forge",
  description: "100% Local-only. Zero Telemetry. No accounts. Your data never leaves your device. This is the privacy protocol of Forge.",
};

export default function PrivacyPage() {
  return (
    <div className="bg-ink-950 min-h-screen text-text-primary selection:bg-ember-600 selection:text-white-hot flex flex-col font-spectral">
      {/* Premium Header */}
      <header className="border-b border-ink-800 px-6 md:px-12 py-6 bg-ink-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-[900px] mx-auto flex justify-between items-center">
          <Link href="/" className="font-cinzel font-bold text-xl tracking-[0.18em] text-ember-500 no-underline hover:text-ember-400 transition-colors duration-300">
            FORGE
          </Link>
          <Link href="/" className="font-cinzel text-xs tracking-[0.15em] text-text-muted hover:text-ember-300 uppercase transition-colors duration-300 no-underline">
            ← Back to Anvil
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 px-6 py-20 max-w-[720px] mx-auto w-full leading-relaxed">
        <p className="font-cinzel text-[10px] tracking-[0.35em] uppercase text-ember-600 mb-4">
          The Harness Protocol
        </p>
        <h1 className="font-cinzel text-3xl md:text-4xl font-bold tracking-tight text-text-primary mb-12">
          Privacy Protocol
        </h1>

        <div className="space-y-10 text-text-muted font-light text-[17px]">
          <p className="text-xl italic text-text-primary font-normal leading-relaxed border-l-2 border-ember-500 pl-5 mb-10">
            "Privacy is not a feature. It is the brand. Forge does not track you, does not harvest your profile, and does not hold keys to your memory. Your work is entirely yours."
          </p>

          <section className="space-y-4">
            <h2 className="font-cinzel text-lg font-semibold text-text-primary tracking-wider uppercase">
              1. Local-Only Storage
            </h2>
            <p>
              Every input, strike, urge log, and personal reflection written inside the Operator's Log is stored entirely on your local device sandbox. We utilize client-side persistent key-stores (Zustand AsyncStorage) and a local sandboxed SQLite database file (`harness.db`).
            </p>
            <p>
              We have no servers. No external sync engines. No remote databases. If you delete the app or wipe your device storage, your data is permanently gone. We cannot recover it because we never had it.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-cinzel text-lg font-semibold text-text-primary tracking-wider uppercase">
              2. Zero Telemetry & Telematics
            </h2>
            <p>
              Forge operates in complete isolation. The application does not contain remote analytics SDKs, crash trackers, or behavior tracking scripts (such as Google Analytics, Firebase, or Mixpanel). Your usage frequency, triggering patterns, and success thresholds remain private.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-cinzel text-lg font-semibold text-text-primary tracking-wider uppercase">
              3. Device Sensors
            </h2>
            <p>
              During active Crucible protocols (such as push-ups or pacing drills), the app reads device motion indicators (the accelerometer sensor) locally to calculate and verify counts. This hardware telemetry is processed inside RAM in real time and is never written to disk or transmitted over network sockets.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-cinzel text-lg font-semibold text-text-primary tracking-wider uppercase">
              4. Biometric Security
            </h2>
            <p>
              If enabled, the biometric authentication toggle (FaceID / TouchID) relies natively on your operating system’s secure enclave protocols. Forge receives only a binary success or failure confirmation from the system controller — we never access, view, or process your biometric markers.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-cinzel text-lg font-semibold text-text-primary tracking-wider uppercase">
              5. Transactions & Subscriptions
            </h2>
            <p>
              Subscription payments are processed securely through the Apple App Store and Google Play billing APIs. We use RevenueCat for client-side receipt validations. All purchases are linked to anonymous transactional IDs generated by the app stores.
            </p>
          </section>

          <section className="space-y-4 border-t border-ink-700 pt-8 mt-12">
            <p className="text-xs text-text-dim uppercase tracking-wider font-cinzel">
              Last Updated: May 2026
            </p>
            <p className="text-xs text-text-dim italic">
              Forge is operated under the Harness Protocol. For privacy queries, refer to the support dashboard.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-ink-800 py-8 text-center bg-ink-950">
        <p className="font-cinzel text-[10px] tracking-widest text-text-dim uppercase">
          © 2026 FORGE · All Rights Reserved
        </p>
      </footer>
    </div>
  );
}
